### ISSUE TITLE
resdata uses setuptools attribute that does not exist

### ISSUE THREAD

**Issue by andreas-el** [equinor/resdata#984]
https://github.com/equinor/komodo-releases/actions/runs/9637565303/job/26577026016

```
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/tmp/f_komodo/actions-runner-01/_temp/venv/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/f_komodo/actions-runner-01/_temp/venv/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/tmp/f_komodo/actions-runner-01/_temp/venv/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-npk4y7ia/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-npk4y7ia/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-npk4y7ia/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-npk4y7ia/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 95, in <module>
      AttributeError: module 'setuptools.command' has no attribute 'test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

```

**Comment by andreas-el** [comment]
This is currently breaking all bleeding builds

**Comment by andreas-el** [comment]
This seems to be the offending line, removing this unclogs the build again.

```
   cmdclass={"test": setuptools.command.test.test},
```

**Comment by andreas-el** [comment]
> Or is it the old way of running `python setup.py test`?

Not sure. Poked Zohar regarding this, and looking at the repo for answers.
We could remove this just to unclog, and gain time to look into why we had this in the first place.
